# Generated by Django 5.1.2 on 2025-04-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='lecture',
            field=models.CharField(default='general', max_length=100),
            preserve_default=False,
        ),
    ]
