# Generated by Django 5.1.2 on 2025-04-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0002_chathistory_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='lecture',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
