# Generated by Django 5.1.2 on 2025-04-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0004_alter_chathistory_options_alter_chathistory_lecture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='correct_answer',
            field=models.TextField(),
        ),
    ]
