# Generated by Django 5.1.2 on 2025-04-29 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0005_alter_quiz_correct_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AddField(
            model_name='chathistory',
            name='quiz_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_model.quiz'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='bot_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user_input',
            field=models.TextField(blank=True),
        ),
    ]
