# Generated by Django 5.1.2 on 2025-05-22 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0007_transcript'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='transcript',
            name='title',
            field=models.CharField(default='Title', max_length=200),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['user', 'lecture', 'title'], name='ai_model_tr_user_id_7545d4_idx'),
        ),
    ]
