# Generated by Django 5.1.2 on 2025-05-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0008_remove_transcript_pdf_file_transcript_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='transcript',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='transcript',
            name='ai_model_tr_user_id_7545d4_idx',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='message_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='bot_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user_input',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
