# Generated by Django 5.1.2 on 2025-05-23 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0009_alter_chathistory_options_alter_quiz_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chathistory',
            constraint=models.UniqueConstraint(fields=('user', 'lecture', 'user_input', 'message_id'), name='unique_chat_entry'),
        ),
    ]
