# Generated by Django 5.1.2 on 2025-05-23 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0010_chathistory_unique_chat_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='chathistory',
            name='unique_chat_entry',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='quiz_id',
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='bot_response',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='message_id',
            field=models.CharField(blank=True, default='message', max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='chathistory',
            constraint=models.UniqueConstraint(fields=('user', 'lecture', 'user_input'), name='unique_chat_entry'),
        ),
    ]
