# Generated by Django 5.1.2 on 2026-08-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0011_alter_chathistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='selected_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
