name: CI for Django + Docker project

on:
  push:
    branches:
      - main
      - testing  
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start services with Docker Compose
        run: docker compose up -d --wait

      - name: Wait for web service to be ready
        run: |
          echo "Waiting for Django to be ready..."
          sleep 10  # çok basic ama iş görüyor

      - name: Run Django tests
        run: docker compose exec -T web python manage.py test

      - name: Tear down
        if: always()
        run: docker compose down -v

